#!/bin/bash

printhelp()
{
   echo "formatBookJson: cat-log json helper"
   echo "Syntax: formatBookJson rootIsbn"
   echo "Valid OpenLibrary json data must be passed into this script via STDIN."
}

if [[ -n "$1" ]]; then
	jq -j '."ISBN:'$1'"."details" | [.title, .subtitle, .edition_name, .publish_date, ([.authors[]|.name] | join(", ")), .publishers[], .isbn_10[0], .isbn_13[0], .number_of_pages] | @tsv'
else
	printhelp
	exit
fi
